language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "AHKhCB3I7WFXOuGDS7KPtfqsxwFZezH9d8347Z0VuIWr2feh4H/l06VSoJxSAROr3N+OtgfivpkrZCRvq5rJjjqiy8qW22VsYd02/QO6tdj+x9R3fPpsCpPEW6jqTyLW8xx+xpKJgArBTFaRP4unmcq6DXJNZe1Lgn9k96OBaP0="
    - secure: "CPlLm0KFxrY+oRZi5/b1Q7rfWG/8qJD9GbRltAqShfMBiJ313DFex4L5bE0Cz/Szcu/WOrhFDBi1WASEEx4XLNlgvAf3S914eTZlm8xChP0pjiszO8bJlhS9VxXL2bVBH352NbR5GDRq+/o0RKZ+DMP9SoQnSaYuaFeOiMTtKME="

install:
   - npm install -g grunt-cli
   - npm -g install bower
   - npm install
   - bower install

script:
   - grunt test:remote

